### ISSUE TITLE
Missing dependency when using a built-in javascript interface

### ISSUE THREAD

**Issue by kennylerma** [apache/royale-compiler#81]
```as3
var url:String = "somefile.mp4";
var data:Object = new Blob([new Uint8Array(url)], {type:"video/mp4"} as BlobPropertyBag));
```
In this case, **{type:"video/mp4"} as BlobPropertyBag** is causing a missing dependency for BlobPropertyBag.
BobPropertyBag is a built-in interface of javascript.  If I don't cast using BlobPropertyBag, it won't compile.  However, when I run it, the dependency is missing.

I also tried creating a new class that implements the interface, but BlobPropertyBag dependency is still missing.
```as3
package interfaces 
{
	public class BlobProperties implements BlobPropertyBag
	{
		private var _type:String = "";
		
		public function BlobProperties() 
		{
			
		}
		
		/* INTERFACE BlobPropertyBag */
		
		public function get type():String 
		{
			return _type;
		}
		
		public function set type(value:String):void 
		{
			_type = value;
		}
	}
}
```

**Comment by aharui** [comment]
What version of Royale are you using?  The nightly build should have BlobPropertyBag for Javascript transpiling.

**Comment by kennylerma** [comment]
Thanks @aharui.  I've been using 0.9.6 version, but this is fixed now in the last successful nightly.  Closing this.

**Comment by carlosrovira** [comment]
Hi @kennylerma,

there's a related question here in SOF about this issue: 

https://stackoverflow.com/questions/63572509/referenceerror-blobpropertybag-is-not-defined

Could you please check it and respond if this issue is fixed (I think so for the responed here), or maybe could be some other issue, or using the code in some wrong way.

thanks
