### ISSUE TITLE
Private constructors in ActionScript

### ISSUE THREAD

**Issue by joshtynjala** [apache/royale-compiler#82]
## Proposed syntax

For singletons:

``` actionscript
package com.example
{
	public class MySingletonClass
	{
		private static var _instance:MySingletonClass;

		public static function get instance():MySingletonClass
		{
			if(!_instance)
			{
				_instance = new MySingletonClass();
			}
			return _instance;
		}

		private function MySingletonClass()
		{
			
		}
	}
}
```

Also useful for classes that are meant to provide static methods only:

``` actionscript
package com.example
{
	public class MyUtils
	{
		public static function utilityFunction1():void {}
		public static function utilityFunction2():void {}
		public static function utilityFunction3():void {}

		private function MyUtils() {}
	}
}
```

## Semantics

At compile time, use of a class with a private constructor in a `new` statement should result in an error, if it is in another class.

``` actionscript
new MySingletonClass(); //error in another class
```

Similar to the `InaccessibleMethodReferenceProblem` that is created when trying to call a method in the wrong scope, there should be a new problem for private constructors with this message:

> Attempted access of inaccessible constructor through a reference with static type MySingletonClass

When this feature is enabled, an alternative to `ConstructorMustBePublicProblem` should be mention `private` too:

> A constructor can only be declared public or private

## Bytecode

In SWF bytecode, the private constructor compiles with `[RoyalePrivateConstructor]` metadata on the parent class:

``` actionscript
package com.example
{
	[RoyalePrivateConstructor]
	public class MySingletonClass
	{
		public function MySingletonClass()
		{
			
		}
	}
}
```

Since we have no control over the bytecode supported by SWF runtimes, this is a workaround that allows us to store extra information that the compiler may use. Additionally, the metadata allows the compiler to recognize if constructor is private when it is loaded from a compiled SWC library.

Metadata added to a constructor definition does not seem to be preserved by the compiler, so that's why it's added to the parent class definition instead.

## How to enable

New ActionScript syntax should be opt-in because IDEs and other tooling may use the Apache Royale compiler with other SDKs that don't support the syntax. Developers can enable private constructors using a new `allow-private-constructors` compiler option.

``` sh
mxmlc -allow-private-constructors App.mxml
```

**Comment by Harbs** [comment]
@joshtynjala Question: When `-allow-private-constructors` is used in a library, does it also need to be allowed in an app which uses the library?

**Comment by joshtynjala** [comment]
@Harbs Yes, I think so.

**Comment by Harbs** [comment]
Hmm. I just tested and I was able to instantiate a class from a library with a private constructor in my project.

That does not seem right. Should we fix this?

**Comment by joshtynjala** [comment]
@Harbs -allow-private-constructors is enabled in both projects? If so, that is indeed a bug.

**Comment by Harbs** [comment]
It compiles with no issues.

Once I enable `-allow-private-constructors` in the project I get an "inaccessible constructor" error.

Maybe `-allow-private-constructors` should just be on be default?

**Comment by joshtynjala** [comment]
Perhaps when `-allow-private-constructors` is disabled in an app project, but it is enabled in a library, it should still be enforced when the app project uses any of the library's classes with private constructors.

**Comment by carlosrovira** [comment]
Hi, I was wondering if a new enhancement like this could be enabled by default since will not affect to old AS3 code since people always have "public" without a way to have other thing? or could this be a problem for someone? Makes this sense?

**Comment by joshtynjala** [comment]
Seems reasonable to enable it by default. It can be done in the SDK config files, like *frameworks/royale-config.xml* and *frameworks/js-config.xml*.

**Comment by carlosrovira** [comment]
Hi Josh,

I'm searching in both files and can't see a tag for private constructors.
Maybe we need to add inside `compiler` tag, in both files, something like the folowing?

`<allow-private-constructors>true</allow-private-constructors>`

**Comment by Harbs** [comment]
I meant that the default setting in the **compiler** should be true. Enabling it in framework code doesn't seem like it'll help fro client code (unless I'm missing what you're saying).

**Comment by Harbs** [comment]
> Perhaps when `-allow-private-constructors` is disabled in an app project, but it is enabled in a library, it should still be enforced when the app project uses any of the library's classes with private constructors.

Or perhaps the "inaccessible constructor" check should just always be on.

**Comment by carlosrovira** [comment]
Hi Harbs, 
what I say is that if people can use private constructors by default will be helpful and don't cause a problem with old code. So for me this kind of new features could be on by default. Same for abstract classes.

In the other hand, since you're working with that now, I think no one better than you to make this changes, since you're testing it too.

thanks

**Comment by joshtynjala** [comment]
> I meant that the default setting in the compiler should be true. Enabling it in framework code doesn't seem like it'll help for client code (unless I'm missing what you're saying).

These config files are used when compiling apps too.

**Comment by joshtynjala** [comment]
> I'm searching in both files and can't see a tag for private constructors.

When an option is missing, the compiler's hardcoded default is used. In that case, the option needs to be added.

> Maybe we need to add inside compiler tag, in both files, something like the folowing?
> <allow-private-constructors>true</allow-private-constructors>

Yes, exactly. It's needed in all of the -config.xml files, though. Not just the two that I mentioned as examples.

**Comment by carlosrovira** [comment]
ok Josh,
I'll add private constructors var to all.
Do you think we can add abstract methods too? I think is the same case, it will not affect older code.
Let me know and I can add both lines to all files
thanks

**Comment by joshtynjala** [comment]
Yes, it seems like enabling abstract classes shouldn't break older code, which couldn't use them.

**Comment by carlosrovira** [comment]
Hi,
it's done. I found 3 classes when building all to test with no "public" word and added it too. So we have now abstract and private constructors on by default :)
thanks!

**Comment by aharui** [comment]
I'm a bit confused.  I don't think I agree that -config.xml files is how to change the default for Royale.  It might be the way to change what the framework and examples use, but then you have to also change the pom.xml files for Maven builds.  IMO, the defaults are in the *Configuration.java files.

My only concern about turning on extra checks is the additional time it might take to compile really large apps.  I haven't looked at how support for private constructors and abstract APIs is implemented in the compiler, but the lookup of such attributes should probably be cached on the IDefinition.  I recently added more caching of IDefinitions because resolving to Definitions is expensive and was happening too frequently, IMO.

**Comment by carlosrovira** [comment]
Hi Alex,
ok, maybe be did this very quickly to be agile. So what do you want to do? do you want to revert? do you want to check IDefinitions?. Let us know your plan. Thanks.

**Comment by joshtynjala** [comment]
> the defaults are in the *Configuration.java files.

As I understand it, our compiler's defaults have always aimed to match the default behavior of the compiler in the classic Flex SDK, and Royale (and FlexJS before that) has always overridden those defaults when necessary using its *-config.xml files.

We can certainly change how we do that, but then we also need to address the situation where the Royale compiler is used for code intelligence in IDEs with frameworks provided by other SDKs. Those other SDKs need the classic defaults (including disabling new features, like private constructors and abstract classes) so that IDEs can report accurate errors. When a new version of Royale is released, maintainers of IDEs using the compiler should not need to figure out which, if any, compiler defaults have changed. It's too low-level and easy to miss.

Maybe this is as simple as providing a new *Configuration.java file that always maintains the classic defaults. IDEs can use that one and be sure that it won't change unexpectedly.

**Comment by aharui** [comment]
@carlosrovira I personally do not want to do anything.  I've got plenty to do.  I am just reminding people to consider performance (and PAYG).  Lots of migrating Flex code will not be using abstract APIs and private constructors but do want reasonable compile times.

@joshtynjala I'm not clear how to swap in different *Configuration.java files.  We do get to set defaults in the royale-config.xml and flex-config.xml files, and that will cover lots of folks, but as soon as someone chooses a different set of defaults, then anything we have set in those files go away.  So the absolute default is set in the *Configuration.java files, from my perspective.  If you only care about the defaults for folks using those config files then that's fine.  It looked like changes were being made to many more -config.xml files just in the Royale framework and not really handling external user's apps.

You are correct that we set defaults so Flex code outputs SWF code in Royale like it did in Flex.  However, in this case, the output of migrating Flex code shouldn't be affected because I don't expect any of the code being compiled would accidentally be using the same syntax we've chosen for private constructors and abstract APIs in Royale.  I just want to make sure we aren't wasting someone's time by checking when we pretty much know there is nothing to find.  But if you do the check once per class (and cache the answer on the IDefinition) instead of once per call to resolve()/resolveType(), then I would think the performance hit would be negligible.

Which legacy IDEs use Royale's compiler?  New IDE's (Moonshine) should just upgrade their code intelligence to handle abstract APIs and private constructors.  It is relatively simple to change flex-compiler-oem to override a default setting for Flash Builder and any other IDEs that call into the Royale compiler.  For any other IDE, do they leave any other clues that the compiler can use to tell it is being called by an IDE?

**Comment by joshtynjala** [comment]
> I'm not clear how to swap in different *Configuration.java files

Don't think of it in terms of someone running the compiler from the command line and choosing a different *Configuration.java class. That's not possible and shouldn't be. However, in VSCode and Moonshine, various compiler classes are instantiated directly in Java code, which gives these IDEs the ability to tell the compiler to use a specific *Configuration.java file. As I recall, they use JSGoogConfiguration for Royale projects, and Configuration for others.

> but as soon as someone chooses a different set of defaults, then anything we have set in those files go away. 

I'm not sure that I follow. Those *-config.xml files override the defaults set in *Configuration.java files, as I mentioned. At least when Royale is the framework being used. Another framework will have its own *-config.xml* files that may need different defaults that are specific to the other framework.

>  It looked like changes were being made to many more -config.xml files just in the Royale framework and not really handling external user's apps.

I haven't looked at what changes were made. My suggestion was to change only the *-config.xml files in the frameworks folder, like *royale-config.xml* and *js-config.xml*. Those will affect external user's apps.

> However, in this case, the output of migrating Flex code shouldn't be affected because I don't expect any of the code being compiled would accidentally be using the same syntax we've chosen for private constructors and abstract APIs in Royale. 

When compiling Royale apps this is true. When providing code intelligence for another framework (like Apache Flex or Feathers), it's not true. In those cases, this syntax should not be allowed.

> But if you do the check once per class (and cache the answer on the IDefinition) instead of once per call to resolve()/resolveType(), then I would think the performance hit would be negligible.

The actual checks that create errors/warnings related to abstract/private classes should happen once. There's a semantic analysis phase in the compiler that checks for inconsistencies, and I added the checks there. This code should not be triggered by every call to resolve()/resolveType()

> Which legacy IDEs use Royale's compiler?

None?

> New IDE's (Moonshine) should just upgrade their code intelligence to handle abstract APIs and private constructors.

It comes for free from the compiler, as long as the compiler options are set correctly. I'm saying that IDEs shouldn't be forced to manually set -allow-abstract-classes=false and -allow-private-constructors=false (and constantly play catch up as new syntax is added) when the compiler is used to provide code intelligence for other frameworks, like Apache Flex or Feathers. The compiler should provide a *Configuration.java that does that.

**Comment by joshtynjala** [comment]
Another option would be to have JSConfiguration or JSGoogConfiguration override the defaults from Configuration (JSGoogConfiguration extends JSConfiguration extends Configuration). Configuration can still keep compatibility with other SDKs, and JSConfiguration (which is only used by Royale) can turn on cool new features without requiring changes to *-config.xml files.

**Comment by carlosrovira** [comment]
If Alex is concerned about Flex code migration (that will never have both of this), I think this can be solved easily as setting flex-config.xml back without this two new defaults, while in Royale, I think we all want this (and many more things to come) on by default (since I assume people coming will want and will be very few don't want and can opt-out).
Thoughts?

**Comment by aharui** [comment]
FWIW, I thought that IntelliJ used a custom *config.xml file to deliver project settings to the compiler.

Also, there are -config.xml files like air-config.xml and airmobile-config.xml that are used when people target AIR.

IIRC, the Royale framework swcs do not use royale-config.xml or flex-config.xml and use custom compile-swf-config.xml and compile-js-config.xml files in the project folders.

IIRC, Maven builds do not use any -config.xml files as the settings are in the POMs.

Of course, I could be wrong...

**Comment by carlosrovira** [comment]
Hi Alex,

thanks for the info, although is not clear to me what do you want to do. I can make new changes, but need to have some guidance or plan based on concrete actions on what's the target we want to pursue.

This is what I solve from above:

 * Maven: I can add to all maven pom.xml the two additional compiler options to all SWCs.
 * Ant: uses compile-swf-config.xml and compile-js-config.xml files? So I should add both here right?
 * -config.xml files: Here we can remove both new lines from flex config files. Let me know if we should do from someone more.

You can modify, add or remove to this so we can have a concrete plan upon we can make the changes

thanks

**Comment by joshtynjala** [comment]
Based on Alex's feedback, which seems to indicate that there are too many config files to update, I'm going to go with this approach, I think:

> Another option would be to have JSConfiguration or JSGoogConfiguration override the defaults from Configuration (JSGoogConfiguration extends JSConfiguration extends Configuration). Configuration can still keep compatibility with other SDKs, and JSConfiguration (which is only used by Royale) can turn on cool new features without requiring changes to *-config.xml files.

I'm busy, so it may be a week or two before I can get to it. Anyone else is welcome to get it done faster. It should just be a couple of function calls in the JSConfiguration constructor.

**Comment by aharui** [comment]
I don't have a concrete recommendation because I don't understand Josh's plan.  That's mainly because I do not understand how he has integrated the compiler into the IDEs.  I trust he understands my concerns and will devise the right solution.

Hopefully the right solution will not require modifying as many -config.xml files as you propose.  It should not require modifying every pom.xml either.  In the release_practice branch I have fixed the poms so that common compiler options can be set in a higher-level pom.  I hope to someday merge release_practice back into develop

**Comment by joshtynjala** [comment]
To configure a project in IDEs, I use the `RoyaleProjectConfigurator` class with either `JSGoogConfiguration` or `Configuration`, depending on the project type. Basically, Royale projects use `JSGoogConfiguration` and non-Royale projects use `Configuration`.

```java
RoyaleProjectConfigurator configurator = null;
if (project instanceof RoyaleJSProject || frameworkSDKIsRoyale)
{
    configurator = new RoyaleProjectConfigurator(JSGoogConfiguration.class);
}
else //swf only
{
    configurator = new RoyaleProjectConfigurator(Configuration.class);
}
```

Later, this `RoyaleProjectConfigurator` is applied to either `RoyaleJSProject` or `RoyaleProject`:

```java
configurator.applyToProject(project);
```

Hopefully, that adds a little context. It's not too different from what Royale's command line compilers do.

`Configuration` cannot actually be used with full Royale projects because it doesn't support all of the new JavaScript related compiler options. Royale's command line compilers use `JSGoogConfiguration` too.

So, `Configuration` is an ideal place to have new features turned off by default for non-Royale projects, and `JSConfiguration` (which is in the hierarchy `JSGoogConfiguration` extends `JSConfiguration` extends `Configuration`) can turn them on by default for Royale projects without affecting non-Royale projects.

**Comment by carlosrovira** [comment]
Hi,
ok since Josh is going to do changes, I'm going to work on other things and left this to him. I think it would be more efficient.
@joshtynjala feel free to revert my commit, although take into account in that commit there was 3 as3 classes without "public" in the constructor, that was making the build fail, so I assume that 3 files are right.

**Comment by joshtynjala** [comment]
@carlosrovira It would probably be better for you to revert it, considering the extra context that you mentioned.

**Comment by carlosrovira** [comment]
Ok, I'll revert it now
thanks Josh :)

**Comment by Harbs** [comment]
@joshtynjala I'm curious why you think the option should be off for non-royale projects. private constructors seems like it's a feature that's completely opt-in. If you don't use it the option shouldn't effect anything.

**Comment by joshtynjala** [comment]
@Harbs If I'm working on a non-Royale project, I would expect to see an appropriate error if I try to use one of Royale's features that isn't supported in my project.

**Comment by Harbs** [comment]
Sure. But why would someone want to specifically disallow private constructors? Why not support it?

**Comment by joshtynjala** [comment]
IDEs use the Royale compiler to provide code intelligence for projects that use frameworks from other SDKs. However, when an IDE compiles a project, it uses the compiler from the selected SDK. Royale's compiler is the only one that understands private constructors. Other compilers do not, so code intelligence should disallow private constructors.

**Comment by Harbs** [comment]
Ah. That's the nuance I was missing. Thanks.
