### ISSUE TITLE
RemoteObject and Listeners on Opretion level - workaround

### ISSUE THREAD

**Issue by saggelopoulos** [apache/royale-compiler#88]
Generated Js code when define listeners at operation level not working 
mailing list thread : 
http://apache-royale-development.20373.n8.nabble.com/RemoteObject-and-Listeners-on-Opretion-level-workaround-tp9534.html

**Comment by aharui** [comment]
This is (currently) a "fact-of-life" for Royale.  RemoteObject is a Proxy so that it can have properties that are the names of the operations (like 'getText').  The compiler cannot know what the type of a Proxy property is for JS output, so it assumes the type of the property is also a Proxy (in order to handle nested ObjectProxy trees).

I suppose the compiler could output lots of code or call a function that tests the value returned and then knows how to properly access the results, but that could be heavy and slow.

In Flash/AIR the runtime knows the type and determines how to access the property.

So at least for now, Royale code may occasionally need more explicit type-casting, mainly when handling XML and Proxy, but also other dynamic objects including dynamic access `obj[propName]`.

So your code will need to explicitly type the Operation so instead of just:

`remoteObject.getText.addEventListener(ResultEvent.RESULT, 
getdataResultHandler);`

which works just fine in SWF, your code will need to be:

`(remoteObject.getText as Operation).addEventListener(ResultEvent.RESULT, 
getdataResultHandler);`

You can use ASDoc comment directives for the method

```
/**
 * @royaleignorecoercion mx.rpc.remoting.Operation
 */
```

to suppress the call to `Language.as()`
