### ISSUE TITLE
Vector.<A>.removeAt does not return object of type A 

### ISSUE THREAD

**Issue by yishayw** [apache/royale-compiler#92]
I get a compile time implicit coercion from Object to A error.

**Comment by greg-dove** [comment]
Yishay, can you please check it following latest change. 
To clarify: this is for vectorEmulationClass=Array only. AS3 conforming Vector implementation did not have this issue. I am a bit confusing at the difference between the title of this issue and the comment about implicit coercion - the title seemed to be the same thing as issue #91 . 
Can you please clarify and/or give me a small example if the issue is related to implicit coercion specifically.

**Comment by yishayw** [comment]
Sorry for the laconic title and description. The description should be:

When compiling 

var vector:Vector.<A> = new Vecor.<A>();
vector.push(new A());
var a:A = vector.removeAt(0);

I get a compile time error: implicit coercion of object of type Object to A

In other words, the compiler thinks Vector.<A>.removeAt() returns an Object, rather than an A.

Issue #91 is different in that it's a runtime error, and the returned object is actually an Array. I would only be able to get to that error by changing the third line in the above snippet to

var a:A = vector.removeAt(0) as A;

I hope that makes it clearer.

**Comment by greg-dove** [comment]
Thanks @yishayw, that's clear - I will address this today my time.

**Comment by greg-dove** [comment]
I believe this is now resolved. I expect that this has been a long-standing bug present in the original Falcon code.
It is currently still present in Adobe Animate. I don't know if it was present in legacy Flex compiler. I'll leave it up to you to verify the fix and close the issue.

**Comment by greg-dove** [comment]
@yishayw I'm assigning this over to you to confirm if the change I made fixes this issue. If yes, please close this ticket, thanks.

**Comment by yishayw** [comment]
Will do. Thanks for working on it.

**Comment by yishayw** [comment]
Fix comfirmed.
